### ISSUE TITLE
why does it return <html> and <body>?

### ISSUE THREAD

**Issue by joperron** [TylerBarnes/gatsby-wordpress-inline-images#9]
Hi!

I would love to use this, I was wondering why it returned those tags? I would love to be able to return only the content divs, is there an underlying reason?

I *could* do a PR

Cheers!

**Comment by TylerBarnes** [comment]
Hey @joperron the reason is due to a change in the way cheerio.js works which is used in this package. I have another branch I'm working on to fix a couple broken settings and I've fixed this on that branch. I haven't had a lot of time to work on it lately but I'll do my best to get to this this week.

**Comment by joperron** [comment]
Very cool, I'm definitely down to test that, thanks!

**Comment by greatestview** [comment]
Same here, when using `react-html-parser` instead of `dangerouslySetInnerHTML`. I’m excited to see that branch being merged. :) But I understand that you’re busy with your other projects, maybe there is some free minute somewhen.

**Comment by TylerBarnes** [comment]
Install `gatsby-wordpress-inline-images@1.2.0` for a fix!
